## Ndarray的创建方式

In [4]:
import numpy as np

data = [1,2,3]

# 创建数组对象
arr1 = np.array(data)
print(arr1.shape) # (3,)

# 比较data和arr1内存地址，结果：不同
print(f"data的内存地址为：{id(data)}")
print(f"arr1的内存地址为：{id(arr1)}")

arr2 = np.array(arr1)
print(f"arr2的id为：{id(arr2)}")

arr3 = np.asarray(arr1)
print(f"arr3的id为：{id(arr3)}") # 创建的内容是ndarray的时候地址相同
arr4 = np.asarray(data)
print(f"arr4的id为：{id(arr4)}")# 创建内容不是ndarray的话地址不同

(3,)
data的内存地址为：2706873820800
arr1的内存地址为：2706231965616
arr2的id为：2706873867728
arr3的id为：2706231965616
arr4的id为：2706873867824


In [5]:
arr = np.zeros((5,5))
arr = np.ones((5,5))
arr = np.empty((5,5))
arr

arr1 = np.zeros_like(arr)
arr1 = np.ones_like(arr)
arr1 = np.empty_like(arr)
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arr = np.full((4, 6), 10)
# arr
arr1 = np.full_like(arr, 7)
arr1

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [6]:
arr = np.arange(0, 10, 2)
print(arr.size)
print(arr.dtype)
arr

5
int64


array([0, 2, 4, 6, 8])

In [7]:
arr2 = np.linspace(0, 10, 5, endpoint=True)
print(arr2)

arr2_1 = np.linspace(0, 10, 5, endpoint=False)
print(arr2_1)

arr3 = np.logspace(start=2, stop=5, num=4, base=2)
print(arr3)

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]
[ 4.  8. 16. 32.]


In [8]:
arr1 = np.random.rand(2,3)
arr1 = np.random.randint(low=0, high=10, size=(2,3))
arr1 = np.random.uniform(low=0, high=10, size=(2,3))
arr1 = np.random.randn(2,3)

arr1



array([[ 0.22824783, -1.69600214, -1.53403051],
       [-1.69074981, -0.49594709,  1.29145724]])

In [9]:
my_arr=  np.matrix("1,2;3,4")

my_arr = np.matrix([[1,2], [3,4]])
my_arr

matrix([[1, 2],
        [3, 4]])

In [10]:
arr1 = np.array([1,2,3], dtype=np.float64)
# print(arr1.dtype)
# arr1

arr2 = np.array([1.2,2.3,3.4], dtype='i8')
# print(arr2.dtype)
# arr2

arr3 = arr1.astype(dtype=np.int64)
print(arr3.dtype)
arr3

int64


array([1, 2, 3])

In [15]:
import numpy as np

arr = np.arange(10)
arr

# 索引2到9（不包含）停止，间隔是2
print(arr[slice(2, 9, 2)])
print(arr[2: 9: 2])

# 索引2 开始到最后
print(arr[2:])

print(arr[2: 9])

[2 4 6 8]
[2 4 6 8]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]


In [16]:
arr = np.random.randint(1, 5, (2, 3))
print(arr)
print(np.cumsum(arr))

[[4 3 2]
 [4 2 2]]
[ 4  7  9 13 15 17]


In [21]:
arr1 = np.random.randint(0, 5, (2, 3))
print(arr1)
print(np.unique(arr1))

[[4 4 2]
 [4 1 0]]
[0 1 2 4]
